name: "Biased circuit-level noise setup"
description: "Setup for a biased circuit-level noise model that can be used for any distance."

error_prob: &prob "prob"
bias: &bias "bias"
bias_pauli: &pauli "bias_pauli"

setup:
  - sq_error_prob: *prob
    cz_error_prob: *prob
    meas_error_prob: *prob
    reset_error_prob: *prob
    idle_error_prob: *prob
    biased_factor: *bias
    biased_pauli: *pauli
